typography_spectrum: 0.6873486570548266
color:
  brandStrength: 0.9210857665166259
  lightness: 0.28931975457817316
  saturation: 0.45214304979890585
  rhythmicContrast: 0.04080445133149624
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/f5b92220-81e6-4e56-945e-ff9b371a6856.jpg
layout_spectrum: 0.17173827881924808
author:
  name: Samuel Ört
  email: orts@student.chalmers.se
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b9f11dbd-8e21-47fb-9530-8cc167e10841.jpg
name: Samuel Ört
navigation:
  - name: LinkedIn
    url: 'http://www.linkedin.com/in/samuelort'
    type: external
